horizontalsystems/bitcoin-kit-ios

WalletKit/WalletKit.xcodeproj/project.pbxproj
WalletKit/WalletKit/Helpers/AddressConverter.swift
WalletKit/WalletKit/Models/Address.swift
WalletKit/WalletKit/Transactions/Builder/TransactionBuilder.swift
WalletKit/WalletKit/Transactions/TransactionExtractor.swift
WalletKit/WalletKitTests/Helpers/AddressConverterTests.swift
WalletKit/WalletKitTests/Transactions/Builder/TransactionBuilderTests.swift
WalletKit/WalletKitTests/Transactions/TransactionExtractorTests.swift

Add address class with type and base58

---

Example/Example/TransactionsController.swift
WalletKit/WalletKit/Core/WalletKit.swift
WalletKit/WalletKit/Managers/UnspentOutputSelector.swift
WalletKit/WalletKit/Models/Address.swift
WalletKit/WalletKit/Models/TransactionOutput.swift
WalletKit/WalletKit/Transactions/Builder/TransactionBuilder.swift
WalletKit/WalletKitTests/Transactions/Builder/TransactionBuilderTests.swift
WalletKit/WalletKitTests/Transactions/TransactionCreatorTests.swift

Add build transaction by address type (p2pkh or p2sh)

---

WalletKit/WalletKit/Core/Logger.swift
WalletKit/WalletKit/Core/WalletKit.swift
WalletKit/WalletKit/Managers/ApiManager.swift
WalletKit/WalletKit/Managers/InitialSyncer.swift
WalletKit/WalletKit/Managers/ProgressSyncer.swift
WalletKit/WalletKit/Managers/Syncer.swift
WalletKit/WalletKit/PeerNetwork/Peer.swift
WalletKit/WalletKit/PeerNetwork/PeerConnection.swift
WalletKit/WalletKit/PeerNetwork/PeerGroup.swift
WalletKit/WalletKit/PeerNetwork/PeerIpManager.swift
WalletKit/WalletKit/Transactions/TransactionProcessor.swift
WalletKit/WalletKitTests/BlockHeaders/HeaderSyncerTests.swift
WalletKit/WalletKitTests/Managers/SyncerTests.swift
WalletKit/WalletKitTests/MockWalletKit.swift
WalletKit/WalletKitTests/Transactions/TransactionProcessorTests.swift

Use singleton Logger for all logs in the project.
Closes #42.

#42: Implement logger class with ability to disable certain logs.

---

WalletKit/WalletKit.xcodeproj/project.pbxproj
WalletKit/WalletKit/BlockHeaders/BlockValidatorFactory.swift
WalletKit/WalletKit/PeerNetwork/BitcoinCashMainNet.swift
WalletKit/WalletKit/PeerNetwork/BitcoinMainNet.swift
WalletKit/WalletKit/PeerNetwork/BitcoinTestNet.swift
WalletKit/WalletKitTests/MockValidatorHelper.swift
WalletKit/WalletKitTests/MockWalletKit.swift
WalletKit/WalletKitTests/PeerNetwork/BitcoinCashMainNetTests.swift
WalletKit/WalletKitTests/PeerNetwork/BitcoinMainNetTests.swift
WalletKit/WalletKitTests/PeerNetwork/BitcoinRegTestNetTests.swift
WalletKit/WalletKitTests/PeerNetwork/BitcoinTestNetTests.swift

- Remove some unused imports.
Closes #66

Add tests for networks validate method (#66)

---

WalletKit/WalletKit/BlockHeaders/HeaderHandler.swift
WalletKit/WalletKit/Crypto/Crypto.swift
WalletKit/WalletKit/HDWallet/HDPublicKey.swift
WalletKit/WalletKitTests/BlockHeaders/HeaderHandlerTests.swift
WalletKit/WalletKitTests/Transactions/TransactionHandlerTests.swift

- HeaderHandler now forks
- Renamed Crypto#secp256k1_pubkey_create method to #createPublicKey
- Fixed TransactionHandlerTests
Closes #58

Fork Hanlder (#58)

---

WalletKit/WalletKit/BlockHeaders/Validators/DAAValidator.swift
WalletKit/WalletKit/BlockHeaders/Validators/LegacyDifficultyAdjustmentValidator.swift
WalletKit/WalletKit/Transactions/TransactionExtractor.swift
WalletKit/WalletKitTests/PeerNetwork/BitcoinCashMainNetTests.swift

- remove ignore optional in DAA validator.
- fix height interval in legacy bitcoin validator.
- fix tests.
- fix extractor type in transaction extractor.
Closes #59

Refactor validators code (#59)

---

WalletKit/WalletKit/Core/WalletKit.swift
WalletKit/WalletKit/HDWallet/HDKeychain.swift
WalletKit/WalletKit/HDWallet/HDPrivateKey.swift
WalletKit/WalletKit/HDWallet/HDPublicKey.swift
WalletKit/WalletKit/HDWallet/HDWallet.swift
WalletKit/WalletKitTests/HDWallet/HDPrivateKeyTests.swift
WalletKit/WalletKitTests/Managers/AddressManagerTests.swift
WalletKit/WalletKitTests/MockWalletKit.swift
WalletKit/WalletKitTests/Transactions/Builder/InputSignerTests.swift

Remove network from HDWallet classes (#103)

---

HSBitcoinKit/HSBitcoinKit/Core/BitcoinKit.swift

- Use sha256 encryption for generating database file name from words.
Closes #111

Encrypt words hash (#111)

---

HSBitcoinKit/HSBitcoinKit/Transactions/TransactionExtractor.swift
HSBitcoinKit/HSBitcoinKitTests/Transactions/TransactionExtractorTests.swift

Refactor transaction extractor #119.

---

HSBitcoinKit/HSBitcoinKit/Core/BitcoinKit.swift
HSBitcoinKitDemo/HSBitcoinKitDemo/Manager.swift

Change NetworkType enum to Coin enum in BitcoinKit (#125)

---

HSBitcoinKit/HSBitcoinKit/Core/DataProvider.swift
HSBitcoinKit/HSBitcoinKit/Models/PublicKey.swift
HSBitcoinKit/HSBitcoinKit/PeerNetwork/BitcoinRegTest.swift
HSBitcoinKit/HSBitcoinKit/PeerNetwork/BitcoinTestNet.swift
HSBitcoinKit/HSBitcoinKit/Serializers/TransactionSerializer.swift
HSBitcoinKit/HSBitcoinKit/Transactions/Builder/InputSigner.swift
HSBitcoinKit/HSBitcoinKit/Transactions/Builder/TransactionBuilder.swift
HSBitcoinKit/HSBitcoinKit/Transactions/Extractors/OpCode.swift
HSBitcoinKit/HSBitcoinKit/Transactions/Extractors/P2WPKHExtractor.swift
HSBitcoinKit/HSBitcoinKit/Transactions/TransactionExtractor.swift
HSBitcoinKit/HSBitcoinKitTests/Transactions/Builder/InputSignerTests.swift
HSBitcoinKit/HSBitcoinKitTests/Transactions/TransactionExtractorTests.swift

Make all type transactions #97

---

HSBitcoinKit/HSBitcoinKit/Transactions/TransactionLinker.swift
HSBitcoinKit/HSBitcoinKitTests/Transactions/TransactionLinkerTests.swift

Set previous output to input (#135)

---

HSBitcoinKit/HSBitcoinKit.xcodeproj/project.pbxproj
HSBitcoinKit/HSBitcoinKit/Core/BitcoinKit.swift
HSBitcoinKit/HSBitcoinKit/Core/Protocols.swift
HSBitcoinKit/HSBitcoinKit/Managers/ReachabilityManager.swift
HSBitcoinKit/HSBitcoinKit/PeerNetwork/Peer.swift
HSBitcoinKit/HSBitcoinKit/PeerNetwork/PeerConnection.swift
HSBitcoinKit/HSBitcoinKit/PeerNetwork/PeerGroup.swift
HSBitcoinKit/HSBitcoinKit/PeerNetwork/PeerHostManager.swift
HSBitcoinKit/HSBitcoinKitTests/PeerNetwork/PeerGroup/PeerManagementTests.swift
HSBitcoinKit/HSBitcoinKitTests/PeerNetwork/PeerHostManagerTests.swift

- PeerGroup stops when network becomes unreachable and starts when it becomes reachable
- PeerHostManager does not remove peer host if there's an error, but network is not reachable

Added ReachabilityManager

---

HSBitcoinKit/HSBitcoinKit/Core/BitcoinKit.swift
HSBitcoinKit/HSBitcoinKit/Core/Logger.swift

Logger minLogLevel (#156)

---

HSBitcoinKit/HSBitcoinKit/Helpers/AddressConverter.swift

Fix bug with wrong bch address in btc kit #155

---

HSBitcoinKit/HSBitcoinKit/Network/Peer/PeerConnection.swift
HSBitcoinKit/HSBitcoinKit/Network/Peer/PeerGroup.swift

Minor bugfixes (#164)

---

HSBitcoinKit/HSBitcoinKit/Core/BitcoinKit.swift
HSBitcoinKit/HSBitcoinKit/Storage/RealmFactory.swift

Define objects in Realm (#174)

---

HSBitcoinKit/HSBitcoinKit.xcodeproj/project.pbxproj
HSBitcoinKit/HSBitcoinKit/Core/BitcoinKit.swift
HSBitcoinKit/HSBitcoinKit/Core/DataProvider.swift
HSBitcoinKit/HSBitcoinKit/Core/Protocols.swift
HSBitcoinKit/HSBitcoinKit/Helpers/AddressConverter.swift
HSBitcoinKit/HSBitcoinKit/Helpers/CashBech32AddressConverter.swift
HSBitcoinKit/HSBitcoinKit/Models/BitcoinPaymentData.swift
HSBitcoinKit/HSBitcoinKit/Network/BitcoinCashTestNet.swift
HSBitcoinKit/HSBitcoinKitTests/Helpers/AddressConverterTests.swift
HSBitcoinKit/HSBitcoinKitTests/Helpers/CashBech32AddressConverterTests.swift

Add parse uri payment request #176

---

HSBitcoinKit/HSBitcoinKitTests/Helpers/AddressConverterTests.swift
HSBitcoinKit/HSBitcoinKitTests/Network/New Group/PeerHostManagerTests.swift

Fix tests broken in ticket 174 (#180)

---

HSBitcoinKit/HSBitcoinKit/Helpers/AddressConverter.swift

Fix bug with short legacy addresses. (#189)

---

HSBitcoinKit/HSBitcoinKit/Core/KitStateProvider.swift
HSBitcoinKit/HSBitcoinKit/Core/Protocols.swift
HSBitcoinKit/HSBitcoinKit/Network/Peer/PeerGroup.swift
HSBitcoinKit/HSBitcoinKitTests/Blocks/KitStateProviderTests.swift
HSBitcoinKit/HSBitcoinKitTests/Network/New Group/PeerGroupTests/PeerDelegateTests.swift
HSBitcoinKit/HSBitcoinKitTests/Network/New Group/PeerGroupTests/PeerGroupTests.swift

PeerGroup should call syncFinished when peer becomes synced (#197)

---

HSBitcoinKit/HSBitcoinKit/Managers/InitialSyncer.swift
HSBitcoinKit/HSBitcoinKit/Network/Peer/Peer.swift
HSBitcoinKit/HSBitcoinKitTests/Managers/InitialSyncerTests.swift

InitialSyncer can have only one syncing process at a time (#200)

---

README.md

Can be previewed in https://github.com/horizontalsystems/bitcoin-kit-ios/tree/readme_update
closes #170

Updated Readme.md file (#170)

---

HSBitcoinKit/HSBitcoinKit/Core/DataProvider.swift
HSBitcoinKit/HSBitcoinKit/Models/Transaction.swift
HSBitcoinKit/HSBitcoinKit/Transactions/TransactionProcessor.swift
HSBitcoinKit/HSBitcoinKitTests/Transactions/TransactionProcessorTests.swift
HSBitcoinKit/HSBitcoinKitTests/Transactions/TransactionPublicKeySetterTests.swift

Process transactions in topological order (#225)

---

HSBitcoinKit.podspec
HSBitcoinKit/HSBitcoinKit/BlockHeaders/BlockValidatorFactory.swift
HSBitcoinKit/HSBitcoinKit/BlockHeaders/Validators/BlockValidatorError.swift
HSBitcoinKit/HSBitcoinKit/BlockHeaders/Validators/HeaderValidator.swift
HSBitcoinKit/HSBitcoinKitTests/BlockHeaders/Validators/HeaderValidatorTests.swift

Proof of Work Validation of blocks (#224)

---

HSBitcoinKit.podspec
HSBitcoinKit/HSBitcoinKit.xcodeproj/project.pbxproj
HSBitcoinKit/HSBitcoinKit/Core/BitcoinKit.swift
HSBitcoinKit/HSBitcoinKit/Managers/InitialSyncer.swift
HSBitcoinKit/HSBitcoinKit/Managers/StateManager.swift
HSBitcoinKit/HSBitcoinKitTests/BlockHeaders/Validators/HeaderValidatorTests.swift
HSBitcoinKit/HSBitcoinKitTests/Managers/InitialSyncerTests.swift
HSBitcoinKit/HSBitcoinKitTests/Managers/StateManagerTests.swift

New wallet

---

HSBitcoinKit/HSBitcoinKit/Managers/UnspentOutputSelector.swift
HSBitcoinKit/HSBitcoinKitTests/Extensions.swift
HSBitcoinKit/HSBitcoinKitTests/Managers/UnspentOutputSelectorTests.swift

- fix fee calculation for single unspent output
- add fee to insufficient funds error

Fix fee calculation

---

HSBitcoinKit/HSBitcoinKit.xcodeproj/project.pbxproj
HSBitcoinKit/HSBitcoinKit/Core/BitcoinKit.swift
HSBitcoinKit/HSBitcoinKit/Core/DataProvider.swift
HSBitcoinKit/HSBitcoinKit/Core/Protocols.swift
HSBitcoinKit/HSBitcoinKit/Models/Transaction.swift
HSBitcoinKit/HSBitcoinKit/Transactions/TransactionProcessor.swift
HSBitcoinKit/HSBitcoinKitTests/Core/DataProviderTests.swift
HSBitcoinKit/HSBitcoinKitTests/Extensions.swift
HSBitcoinKit/HSBitcoinKitTests/Transactions/TransactionProcessorTests.swift
HSBitcoinKitDemo/HSBitcoinKitDemo/Manager.swift
HSBitcoinKitDemo/HSBitcoinKitDemo/TransactionsController.swift

Tx api change

---

HSBitcoinKit/HSBitcoinKit/Transactions/Builder/TransactionBuilder.swift

Make max sequence for any input when send transaction

---

HSBitcoinKit/HSBitcoinKit/Core/BitcoinKit.swift
HSBitcoinKit/HSBitcoinKit/Core/KitStateProvider.swift
HSBitcoinKit/HSBitcoinKit/Core/Protocols.swift
HSBitcoinKit/HSBitcoinKitTests/Blocks/KitStateProviderTests.swift
HSBitcoinKitDemo/HSBitcoinKitDemo/BalanceController.swift
Podfile.lock

- Send updates only on change sync state.
- Update pods
closes #221

Add syncState to provider and kit

---

HSBitcoinKit/HSBitcoinKit/Managers/InitialSync/InitialSyncer.swift

Return fill gap when syncing

---

HSBitcoinKit/HSBitcoinKit/Blocks/BlockSyncer.swift
HSBitcoinKit/HSBitcoinKit/Core/BitcoinKit.swift
HSBitcoinKit/HSBitcoinKit/Core/Protocols.swift
HSBitcoinKit/HSBitcoinKit/Managers/InitialSync/BlockHashFetcher.swift
HSBitcoinKit/HSBitcoinKit/Models/BlockHash.swift
HSBitcoinKit/HSBitcoinKit/Models/SentTransaction.swift
HSBitcoinKit/HSBitcoinKit/Storage/GrdbStorage.swift
HSBitcoinKit/HSBitcoinKit/Storage/RealmFactory.swift
HSBitcoinKit/HSBitcoinKit/Transactions/TransactionSyncer.swift
HSBitcoinKit/HSBitcoinKitTests/Blocks/BlockSyncerTests.swift
HSBitcoinKit/HSBitcoinKitTests/Managers/InitialSync/BlockDiscoveryBatchTest.swift
HSBitcoinKit/HSBitcoinKitTests/Managers/InitialSyncerTests.swift
HSBitcoinKit/HSBitcoinKitTests/Network/New Group/PeerTask/GetMerkleBlocksTaskTests.swift
HSBitcoinKit/HSBitcoinKitTests/Transactions/TransactionSyncerTests.swift

- SentTransaction moved to GRDB
- TransactionSyncer works with IStorage

Replace database to grdb

---

HSBitcoinKit.podspec
HSBitcoinKit/HSBitcoinKit/Core/BitcoinKit.swift
HSBitcoinKit/HSBitcoinKit/Core/DataProvider.swift
HSBitcoinKit/HSBitcoinKit/Core/Protocols.swift
HSBitcoinKit/HSBitcoinKit/Managers/BcoinProvider.swift
HSBitcoinKit/HSBitcoinKit/Managers/FeeRateManager.swift
HSBitcoinKit/HSBitcoinKit/Managers/IpfsApi.swift
HSBitcoinKit/HSBitcoinKit/Models/FeeRate.swift
HSBitcoinKit/HSBitcoinKitTests/Core/DataProviderTests.swift
HSBitcoinKit/HSBitcoinKitTests/Managers/FeeRateManagerTests.swift
Podfile
Podfile.lock

Implement customizable fee (#262)

---

HSBitcoinKit/HSBitcoinKit/Core/AbstractKit.swift
HSBitcoinKit/HSBitcoinKit/Core/BitcoinCashKit.swift
HSBitcoinKit/HSBitcoinKit/Core/BitcoinCore.swift
HSBitcoinKit/HSBitcoinKit/Core/BitcoinKit.swift
HSBitcoinKit/HSBitcoinKit/Dash/DashKit.swift
HSBitcoinKit/HSBitcoinKit/Managers/BcoinProvider.swift
HSBitcoinKit/HSBitcoinKit/Managers/IpfsApi.swift
HSBitcoinKit/HSBitcoinKit/Models/FeeRate.swift
HSBitcoinKitDemo/HSBitcoinKitDemo/Manager.swift
HSBitcoinKitDemo/HSBitcoinKitDemo/SendController.swift
HSBitcoinKitDemo/HSBitcoinKitDemo/SendController.xib

- Change api key
- Change default coin to BTC
- Add support fee rate priority
- Change UI
closes #277

Add custom fee rate (#277)

---

HSBitcoinKit/HSBitcoinKit.xcodeproj/project.pbxproj
HSBitcoinKit/HSBitcoinKit/Core/BitcoinCoreBuilder.swift
HSBitcoinKit/HSBitcoinKitTests/Network/New Group/PeerGroupTests/IPeerGroupTests.swift
HSBitcoinKit/HSBitcoinKitTests/Network/New Group/PeerGroupTests/PeerDelegateTests.swift
HSBitcoinKit/HSBitcoinKitTests/Network/New Group/PeerManagerTests.swift

Merge prod

---

BitcoinCashKit/BitcoinCashKit.xcodeproj/project.pbxproj
BitcoinCashKit/BitcoinCashKit.xcodeproj/xcshareddata/xcschemes/BitcoinCashKitTests.xcscheme
BitcoinCore/BitcoinCore.xcodeproj/project.pbxproj
BitcoinCore/BitcoinCore.xcodeproj/xcshareddata/xcschemes/BitcoinCoreTests.xcscheme
BitcoinCore/BitcoinCore/Core/Logger.swift
BitcoinCore/BitcoinCore/Helpers/CashAddrBech32.swift
BitcoinCore/BitcoinCore/Helpers/Serialization.swift
BitcoinKit/BitcoinKit.xcodeproj/project.pbxproj
DashKit/DashKitTests/InstantSend/TransactionLockVoteValidatorTests.swift

- Remove warnings
- Fix file orders
- Add schemes

Minor fixes

---

BitcoinCore/BitcoinCore/Blocks/InitialBlockDownload.swift
BitcoinCore/BitcoinCore/Core/AbstractKit.swift
BitcoinCore/BitcoinCore/Core/DataProvider.swift
BitcoinCore/BitcoinCore/Managers/UnspentOutputSelector.swift
BitcoinCore/BitcoinCore/Models/PublicKey.swift
BitcoinCore/BitcoinCore/Network/Peer/Peer.swift
BitcoinCore/BitcoinCore/Transactions/Builder/TransactionBuilder.swift
BitcoinKit/BitcoinKit/Core/BitcoinKit.swift

Fix sending witness transaction. (#300)

---

BitcoinCore/BitcoinCore/Network/Peer/Peer.swift

Peer doesn't call delegate.peerDidConnect if version message validation has not passed

---

BitcoinCashKit/BitcoinCashKit/Core/BitcoinCashKit.swift
BitcoinCore/BitcoinCore/Blocks/InitialBlockDownload.swift
BitcoinCore/BitcoinCore/Core/AbstractKit.swift
BitcoinCore/BitcoinCore/Core/BitcoinCore.swift
BitcoinCore/BitcoinCore/Core/BitcoinCoreBuilder.swift
BitcoinCore/BitcoinCore/Core/Protocols.swift
BitcoinCore/BitcoinCore/Network/Peer/PeerGroup.swift
BitcoinCore/BitcoinCore/Network/Peer/PeerManager.swift
BitcoinCore/BitcoinCore/Network/SendTransactionsOnPeerSynced.swift
BitcoinKit/BitcoinKit/Core/BitcoinKit.swift
DashKit/DashKit/Core/DashKit.swift
DashKit/DashKit/Core/Protocols.swift
DashKit/DashKit/MasternodeList/MasternodeListSyncer.swift
Demo/Demo/Manager.swift

- Bugfix
- Add timeout when requesting masternode list diff
- Remove peer if it is disconnected with unknown Exception
closes #314

Fix syncing masternode list (#314)

---

BitcoinCore/BitcoinCore/Blocks/InitialBlockDownload.swift
BitcoinCore/BitcoinCore/Core/AbstractKit.swift
BitcoinCore/BitcoinCore/Core/BitcoinCore.swift
BitcoinCore/BitcoinCore/Managers/SyncManager.swift
BitcoinCore/BitcoinCore/Network/Peer/Peer.swift
BitcoinCore/BitcoinCore/Network/Peer/PeerGroup.swift
BitcoinCore/BitcoinCoreTests/Transactions/TransactionSyncerTests.swift
Demo/Demo/BalanceController.swift
Demo/Demo/BalanceController.xib
Demo/Demo/Manager.swift

AbstractKit stop

---

Demo/Demo.xcodeproj/project.pbxproj
Demo/Demo/AppDelegate.swift
Demo/Demo/Controllers/BalanceController.swift
Demo/Demo/Controllers/ReceiveController.swift
Demo/Demo/Controllers/SendController.swift
Demo/Demo/Controllers/TransactionsController.swift
Demo/Demo/Core/Manager.swift

Update demo app to init adapters and kits in background

---

Demo/Demo/Adapters/BaseAdapter.swift
Demo/Demo/Adapters/BitcoinAdapter.swift
Demo/Demo/Adapters/BitcoinCashAdapter.swift
Demo/Demo/Adapters/DashAdapter.swift
Demo/Demo/Configuration.swift
Demo/Demo/Controllers/Cells/TransactionCell.swift
Demo/Demo/Controllers/TransactionsController.swift

- fix GUI issues in transactions controller
- extract minLogLevel configuration into Configuration class
- run start and clear method in background thread
#319

Demo app improvements

---

BitcoinCashKit/BitcoinCashKit/Core/BitcoinCashKit.swift
BitcoinCore/BitcoinCore.xcodeproj/project.pbxproj
BitcoinCore/BitcoinCore/Core/BitcoinCoreBuilder.swift
BitcoinCore/BitcoinCore/Core/Protocols.swift
BitcoinCore/BitcoinCore/Managers/ApiManager.swift
BitcoinCore/BitcoinCore/Managers/InitialSync/BCoinApi.swift
BitcoinCore/BitcoinCore/Managers/InitialSync/BlockHashFetcher.swift
BitcoinCore/BitcoinCore/Managers/InitialSync/BlockHashFetcherHelper.swift
BitcoinCore/BitcoinCore/Managers/InitialSync/SyncTransactionItem.swift
BitcoinKit/BitcoinKit/Core/BitcoinKit.swift
DashKit/DashKit.xcodeproj/project.pbxproj
DashKit/DashKit/Core/DashKit.swift
DashKit/DashKit/Managers/DashAddressSelector.swift
DashKit/DashKit/Managers/InitialSync/InsightApi.swift
DashKit/DashKit/Network/MainNet.swift

Add initial sync for dash

---

DashKit/DashKit/Managers/InitialSync/InsightApi.swift

Add pagination for insight api explorer

---

BitcoinCore/BitcoinCore/Blocks/InitialBlockDownload.swift
BitcoinCore/BitcoinCore/Managers/SyncedReadyPeerManager.swift
BitcoinCore/BitcoinCore/Network/Peer/PeerGroup.swift

Fix race condition bug (#334)

---

BitcoinCore/BitcoinCoreTests/Blocks/MerkleBlockValidatorTests.swift
BitcoinCore/BitcoinCoreTests/Helpers/MerkleBranchTests.swift
DashKit/DashKit.xcodeproj/project.pbxproj
DashKit/DashKit/Core/DashKit.swift
DashKit/DashKit/Core/Protocols.swift
DashKit/DashKit/DashKitErrors.swift
DashKit/DashKit/MasternodeList/MasternodeListManager.swift
DashKit/DashKit/Models/Quorum.swift
DashKit/DashKit/Network/Messages/MasternodeListDiffMessage.swift
DashKit/DashKit/Network/Parsers/MasternodeListDiffMessageParser.swift
DashKit/DashKit/Network/Parsers/QuorumParser.swift
DashKit/DashKit/QuorumList/QuorumListManager.swift
DashKit/DashKit/QuorumList/QuorumListMerkleRootCalculator.swift
DashKit/DashKit/QuorumList/QuorumSortedList.swift
DashKit/DashKit/Storage/DashGrdbStorage.swift
DashKit/DashKitTests/MasternodeList/MasternodeListManagerTests.swift

Add masternodes quorum parsing in mnDiff message.

---

BitcoinCore/BitcoinCore/Network/Peer/Peer.swift
DashKit/DashKit/Network/MainNet.swift

- Disconnect peer with outdated version protocol

Increase Dash protocol version for mainnet

---

DashKit/DashKit/Core/DashKit.swift

remove limitation of 4 utxo in Dash instant send 

---

BitcoinCore/BitcoinCore/Blocks/InitialBlockDownload.swift
BitcoinCore/BitcoinCore/Core/BitcoinCoreBuilder.swift
BitcoinCore/BitcoinCore/Core/BloomFilterLoader.swift
BitcoinCore/BitcoinCore/Core/Protocols.swift
BitcoinCore/BitcoinCore/Models/PeerAddress.swift
BitcoinCore/BitcoinCore/Network/Peer/Peer.swift
BitcoinCore/BitcoinCore/Network/Peer/PeerAddressManager.swift
BitcoinCore/BitcoinCore/Network/Peer/PeerGroup.swift
BitcoinCore/BitcoinCore/Network/Peer/PeerManager.swift
BitcoinCore/BitcoinCore/Storage/GrdbStorage.swift

Peer selection by connection time

---

BitcoinCore/BitcoinCore/Storage/GrdbStorage.swift
BitcoinCore/BitcoinCore/Transactions/TransactionProcessor.swift
BitcoinCore/BitcoinCoreTests/Transactions/TransactionProcessorTests.swift

Ignore relay tx from mempool if it already in block 

---

BitcoinCashKit/BitcoinCashKit/Blocks/Validators/EDAValidator.swift
BitcoinCashKit/BitcoinCashKit/Core/BitcoinCashKit.swift
BitcoinCore/BitcoinCore/Blocks/Validators/BlockValidatorChain.swift
DashKit/DashKit/Core/DashKit.swift

- Fix peer's count for dash and bitcoinCash

Fix full sync block validation

---

BitcoinCashKit/BitcoinCashKit/Blocks/Validators/EDAValidator.swift
DashKit/DashKit/Blocks/Validators/DarkGravityWaveTestNetValidator.swift
DashKit/DashKit/Blocks/Validators/DarkGravityWaveValidator.swift
DashKit/DashKit/Core/DashKit.swift
Demo/Demo/Configuration.swift

Fix bitcoincash block validation and dash testnet validation

---

BitcoinCashKit/BitcoinCashKit/Core/BitcoinCashKit.swift
BitcoinCore/BitcoinCore.xcodeproj/project.pbxproj
BitcoinCore/BitcoinCore/Managers/InitialSync/InsightApi.swift
DashKit/DashKit.xcodeproj/project.pbxproj

Integrate insight api initial sync for bitcoincash

---

README.md

Readme.md updated (#375)

---

BitcoinCashKit/BitcoinCashKit.xcodeproj/project.pbxproj
BitcoinCashKit/BitcoinCashKit/Blocks/Validators/ForkValidator.swift
BitcoinCashKit/BitcoinCashKit/Core/BitcoinCashKit.swift
BitcoinCashKit/BitcoinCashKit/Core/BitcoinCoreCompatibility.swift
BitcoinCashKit/BitcoinCashKit/Core/Protocols.swift
BitcoinCashKit/BitcoinCashKitTests/Blocks/Validators/EDAValidatorTests.swift
BitcoinCashKit/BitcoinCashKitTests/Blocks/Validators/ForkValidatorTests.swift
BitcoinCore/BitcoinCore/Core/BitcoinCoreErrors.swift

when validate forked- height block 
closes #378

Add fork validator for check expected blockHash

---

BitcoinCore/BitcoinCore/Blocks/InitialBlockDownload.swift
BitcoinCore/BitcoinCore/Core/KitStateProvider.swift
BitcoinCore/BitcoinCore/Core/Protocols.swift
BitcoinCore/BitcoinCore/Network/TransactionSender.swift
Demo/Demo/Controllers/WordsController.swift
Demo/Demo/Controllers/WordsController.xib
Demo/Demo/Core/Manager.swift

Notify 'synced' when enough peers are synced (#369)

---

BitcoinCashKit/BitcoinCashKit/Core/BitcoinCashKit.swift
BitcoinKit/BitcoinKit/Core/BitcoinKit.swift
DashKit/DashKit/Core/DashKit.swift

Re-add 'confirmationsThreshold' parameter to kits (#380)

---

BitcoinKit/BitcoinKit/Network/MainNet.swift

Fix bug with wrong checkpoint block timestamp 

---

BitcoinCore/BitcoinCore/Managers/BloomFilterManager.swift
BitcoinCore/BitcoinCore/Transactions/TransactionProcessor.swift
BitcoinKit/BitcoinKit/Network/TestNet.swift

- Update testnet  checkpoint block.
closes #397

Fix bug with wpkhSh transaction restoring

---

BitcoinCore/BitcoinCore/Core/AbstractKit.swift
BitcoinCore/BitcoinCore/Core/BitcoinCore.swift
BitcoinCore/BitcoinCore/Core/BitcoinCoreBuilder.swift
BitcoinCore/BitcoinCore/Core/Protocols.swift
BitcoinCore/BitcoinCore/Transactions/Builder/TransactionBuilder.swift
BitcoinCore/BitcoinCore/Transactions/TransactionCreator.swift
BitcoinCore/BitcoinCoreTests/Transactions/Builder/TransactionBuilderTests.swift
BitcoinCore/BitcoinCoreTests/Transactions/TransactionCreatorTests.swift
DashKit/DashKit/Core/DashKit.swift
Demo/Demo/Adapters/BaseAdapter.swift
Demo/Demo/Adapters/BitcoinAdapter.swift
Demo/Demo/Configuration.swift

Ability to set change output script type (#407)

---

BitcoinCashKit.swift.podspec
BitcoinCashKit/BitcoinCashKit/Core/BitcoinCashKit.swift
BitcoinCore.swift.podspec
BitcoinCore/BitcoinCore/Helpers/DirectoryHelper.swift
BitcoinKit.swift.podspec
BitcoinKit/BitcoinKit/Core/BitcoinKit.swift
DashKit.swift.podspec
DashKit/DashKit/Core/DashKit.swift
Demo/Demo/Adapters/BitcoinAdapter.swift
Demo/Demo/Adapters/BitcoinCashAdapter.swift
Demo/Demo/Adapters/DashAdapter.swift

Ability to clear wallets except specified ones

---

BitcoinCore/BitcoinCore/Core/BaseTransactionInfoConverter.swift
BitcoinCore/BitcoinCore/Core/Protocols.swift
BitcoinCore/BitcoinCore/Models/TransactionInfo.swift
DashKit/DashKit/Models/DashTransactionInfo.swift
Demo/Demo/Adapters/BaseAdapter.swift
Demo/Demo/Controllers/Cells/TransactionCell.swift
Demo/Demo/Core/TransactionRecord.swift

TransactionInfo has fee and correct 'amount' field
closes #416

Add fee to TransactionInfo

---

BitcoinCore/BitcoinCore/Core/BitcoinCoreBuilder.swift
BitcoinCore/BitcoinCore/Core/Protocols.swift
BitcoinCore/BitcoinCore/Transactions/Builder/TransactionBuilder.swift
BitcoinCore/BitcoinCore/Transactions/TransactionCreator.swift
BitcoinCore/BitcoinCoreTests/Transactions/Builder/TransactionBuilderTests.swift
BitcoinCore/BitcoinCoreTests/Transactions/TransactionCreatorTests.swift

Set last blocks height to transaction nLockTime field

---

BitcoinCore/BitcoinCore/Core/AbstractKit.swift
BitcoinCore/BitcoinCore/Core/BitcoinCore.swift
BitcoinCore/BitcoinCore/Core/BitcoinCoreBuilder.swift

Add status info to BitcoinCore

---

BitcoinCore/Classes/Core/DataProvider.swift

Use addressConverter#convert(publicKey:type) method in debugInfo

---

BitcoinCashKit.swift.podspec
BitcoinCore.swift.podspec
BitcoinCore/Classes/Core/Protocols.swift
BitcoinCore/Classes/Network/Messages/VersionMessage.swift
BitcoinKit.swift.podspec
DashKit.swift.podspec
Example/BitcoinKit/Info.plist
Example/Podfile.lock
Hodler.swift.podspec

- Update pods versions
closes #465

Filter out peers with NODE_BLOOM service flag set off

---

BitcoinCashKit.swift.podspec
BitcoinCore.swift.podspec
BitcoinCore/Classes/Storage/GrdbStorage.swift
BitcoinKit.swift.podspec
DashKit.swift.podspec
Hodler.swift.podspec

Update to 0.13.2 all dependencies

Fix bug with grdb validOrInvalid transaction query. Update pod versions.

---

BitcoinCore/Classes/Transactions/TransactionProcessor.swift

Update timestamp when transaction become in block.

Update tx only when change status. 

---

BitcoinCore.swift.podspec
BitcoinCore/Classes/Core/Protocols.swift
BitcoinCore/Classes/Storage/GrdbStorage.swift
BitcoinCore/Classes/Transactions/TransactionMediator.swift
BitcoinCore/Classes/Transactions/TransactionProcessor.swift

- Unique transactions from inputs query
- Remove repeating update transactions
- Check conflictingHash for invalidating transaction

Refactor Core double spend handling. Update pod

---

BitcoinCore.swift.podspec
BitcoinCore/Classes/Helpers/Bip69.swift
BitcoinCore/Classes/Transactions/Builder/InputSetter.swift
BitcoinCore/Classes/Transactions/Builder/MutableTransaction.swift
DashKit.swift.podspec
DashKit/Classes/Core/DashExtensions.swift
Example/BitcoinKit.xcodeproj/project.pbxproj
Example/Podfile.lock
Example/Tests/BitcoinCore/Helpers/Bip69Tests.swift
Example/Tests/BitcoinCore/Transactions/TransactionProcessorTests.swift
Example/Tests/BitcoinCore/Transactions/TransactionSyncerTests.swift

Bip 69 implementation

---

BitcoinCore/Classes/Blocks/InitialBlockDownload.swift
BitcoinCore/Classes/Core/BitcoinCore.swift
BitcoinCore/Classes/Core/BitcoinCoreBuilder.swift
BitcoinCore/Classes/Core/KitStateProvider.swift
BitcoinCore/Classes/Core/Protocols.swift
BitcoinCore/Classes/Managers/InitialSync/InitialSyncer.swift
BitcoinCore/Classes/Managers/SyncManager.swift
BitcoinCore/Classes/Network/Peer/PeerGroup.swift
Example/BitcoinKit/Configuration.swift
Example/BitcoinKit/Controllers/BalanceController.swift
Example/BitcoinKit/Controllers/Cells/BalanceCell.swift
Example/BitcoinKit/Controllers/Cells/BalanceCell.xib
Example/Podfile.lock
Example/Tests/BitcoinCore/Extensions.swift

- move StateManager from InitialSyncer to SyncManager
- add states to SyncManager

Refactor SyncManager and add error to .notSynced state

---

BitcoinCashKit/Classes/Core/BitcoinCashKit.swift
BitcoinCore/Classes/Managers/InitialSync/InsightApi.swift
BitcoinKit/Classes/Core/BitcoinKit.swift

Make separate addresses in insight requests by 99 addresses.

Update insight api links.

---

BitcoinCore/Classes/Core/AbstractKit.swift
BitcoinCore/Classes/Core/BitcoinCore.swift
BitcoinCore/Classes/Core/Protocols.swift
BitcoinCore/Classes/Transactions/TransactionCreator.swift
Example/Tests/BitcoinCore/Blocks/BlockSyncerTests.swift
Example/Tests/BitcoinCore/Transactions/TransactionCreatorTests.swift

Add #createRawTransaction method to AbstractKit

---

DashKit/Classes/Network/Messages/TransactionMessageParser.swift

Check if transaction is special and has extraPayload

Fix parsing Dash version. 
