horizontalsystems/bitcoin-kit-ios

WalletKit/WalletKit/BlockHeaders/Validators/DAAValidator.swift, WalletKit/WalletKit/PeerNetwork/BitcoinCashMainNet.swift, WalletKit/WalletKit/Scripts/ScriptConverter.swift
- Fix bug with suitable block, when 2 blocks have equal timestamp.
- Fix bug with crash when parsing script data has wrong push command.
- Add block in BitcoinMainNet for testing hardfork after refactor syncers.
Closes #79
=> Check Bitcoin Cash algorithm (#79)

WalletKit/WalletKit.xcodeproj/project.pbxproj, WalletKit/WalletKit/Core/Logger.swift, WalletKit/WalletKit/Core/WalletKit.swift, WalletKit/WalletKit/PeerNetwork/HostDiscovery.swift, WalletKit/WalletKit/PeerNetwork/PeerGroup.swift, WalletKit/WalletKit/PeerNetwork/PeerHostManager.swift, WalletKit/WalletKitTests/MockWalletKit.swift, WalletKit/WalletKitTests/PeerNetwork/PeerHostManagerTests.swift
- Renamed PeerIpManager to PeerHostManager
- Covered PeerHostManager with tests
- Moved PeerHostManager#lookup to HostDiscovery for testability
- Fixed bug in #76 
Closes #76
=> PeerHostManagerTests (#76)

WalletKit/WalletKit/PeerNetwork/PeerHostManager.swift, WalletKit/WalletKitTests/PeerNetwork/PeerHostManagerTests.swift
- Renamed connectedHosts to usedHosts
- usedHosts are mutated within separate DispatchQueue
- collecting is renamed to 'collected'. Now, DNS lookup performs only once.
=> PeerHostManager bugfix #76

HSBitcoinKit/HSBitcoinKit/Core/Protocols.swift, HSBitcoinKit/HSBitcoinKit/Managers/InitialSyncer.swift, HSBitcoinKit/HSBitcoinKit/Network/BitcoinCashMainNet.swift, HSBitcoinKit/HSBitcoinKit/Network/BitcoinCashTestNet.swift, HSBitcoinKit/HSBitcoinKit/Network/BitcoinMainNet.swift, HSBitcoinKit/HSBitcoinKit/Network/BitcoinRegTest.swift, HSBitcoinKit/HSBitcoinKit/Network/BitcoinTestNet.swift, HSBitcoinKit/HSBitcoinKit/Network/Peer/PeerGroup.swift, HSBitcoinKit/HSBitcoinKit/Transactions/TransactionCreator.swift, HSBitcoinKit/HSBitcoinKitTests/Managers/InitialSyncerTests.swift, HSBitcoinKit/HSBitcoinKitTests/Network/New Group/PeerGroupTests/IPeerGroupTests.swift
- InitialSyncer runs AddressManager#fillGap before API sync
- InitialSyncer shouldn't start API sync if network is not syncableFromApi
- PeerGroup#sendPendingTransactions throws exception if there's no peers connected or not all peers synced
Closes #146
=> "Address receive" and "transaction send" when not synced (#146)

HSBitcoinKit/HSBitcoinKit/Blocks/BlockSyncer.swift, HSBitcoinKit/HSBitcoinKit/Network/BitcoinMainNet.swift, HSBitcoinKit/HSBitcoinKitTests/Blocks/BlockSyncerTests.swift
- Check blockHashes for existence before adding
- Updated BitcoinMainNet checkpoint
closes #169
=> Fix Duplicate blockHashes bug (#169)

HSBitcoinKit/HSBitcoinKit/Blocks/Blockchain.swift, HSBitcoinKit/HSBitcoinKit/Core/BitcoinKit.swift, HSBitcoinKit/HSBitcoinKit/Core/DataProvider.swift, HSBitcoinKit/HSBitcoinKit/Core/Protocols.swift, HSBitcoinKit/HSBitcoinKit/Managers/FeeRateManager.swift, HSBitcoinKit/HSBitcoinKit/Managers/FeeRateSyncer.swift, HSBitcoinKit/HSBitcoinKit/Transactions/TransactionCreator.swift, HSBitcoinKit/HSBitcoinKit/Transactions/TransactionProcessor.swift, HSBitcoinKit/HSBitcoinKitTests/Blocks/BlockSyncerTests.swift, HSBitcoinKit/HSBitcoinKitTests/Blocks/BlockchainTests.swift, HSBitcoinKit/HSBitcoinKitTests/Core/DataProviderTests.swift, HSBitcoinKit/HSBitcoinKitTests/Transactions/TransactionCreatorTests.swift, HSBitcoinKit/HSBitcoinKitTests/Transactions/TransactionProcessorTests.swift, HSBitcoinKitDemo/HSBitcoinKitDemo/BalanceController.swift, HSBitcoinKitDemo/HSBitcoinKitDemo/Manager.swift, README.md
- Change BitcoinKit interface. Separate handle deleted transactions and updated/inserted transactions
- Add BlockchainDataListener for transaction and block updates
- Incapsulate proccess logic in TransactionProcessor class
closes #237 
closes #245
=> Use listener instead realm observer in data provider

HSBitcoinKit/HSBitcoinKit/Network/Messages/InventoryMessage.swift, HSBitcoinKit/HSBitcoinKit/Transactions/TransactionProcessor.swift, HSBitcoinKit/HSBitcoinKitTests/Transactions/TransactionProcessorTests.swift, HSBitcoinKitDemo/HSBitcoinKitDemo/BalanceController.swift
- Fix bug with wrong update transaction until process existing tx.
- Initialize bitcoinKit on main thread (UI update)
closes #169
=> Ignore duplicate primary blockHash when process inventory item

HSBitcoinKit/HSBitcoinKit.xcodeproj/project.pbxproj, HSBitcoinKit/HSBitcoinKit/Core/BitcoinKit.swift, HSBitcoinKit/HSBitcoinKit/Core/DataProvider.swift, HSBitcoinKit/HSBitcoinKit/Core/Protocols.swift, HSBitcoinKit/HSBitcoinKit/Core/Signal.swift, HSBitcoinKit/HSBitcoinKit/Managers/FeeRateManager.swift, HSBitcoinKit/HSBitcoinKit/Managers/InitialSync/InitialSyncer.swift, HSBitcoinKit/HSBitcoinKit/Managers/ReachabilityManager.swift, HSBitcoinKit/HSBitcoinKit/Network/Peer/PeerGroup.swift, HSBitcoinKit/HSBitcoinKitTests/Core/DataProviderTests.swift, HSBitcoinKit/HSBitcoinKitTests/Managers/FeeRateManagerTests.swift, HSBitcoinKit/HSBitcoinKitTests/Managers/InitialSyncerTests.swift, HSBitcoinKit/HSBitcoinKitTests/Network/New Group/PeerGroupTests/IPeerGroupTests.swift, HSBitcoinKit/HSBitcoinKitTests/Network/New Group/PeerGroupTests/PeerDelegateTests.swift, HSBitcoinKit/HSBitcoinKitTests/Network/New Group/PeerGroupTests/PeerGroupTests.swift, HSBitcoinKitDemo/HSBitcoinKitDemo/Manager.swift
- Add network handling to initial syncer
- Add new reachability manager
- Add stop method to initial syncer, stop peer group throw it
- Ignore signal to update balance if it's state not changed
- Make test project create bitcoinKit on main thread
closes #243
=> Fix BTC stop syncing when api sync failed

HSBitcoinKit/HSBitcoinKit/Blocks/BlockSyncer.swift
- Don't request blocks earlier than local checkpoint block
closes #258
=> Fix issue with syncing expired peers

HSBitcoinKit/HSBitcoinKit/Core/Protocols.swift, HSBitcoinKit/HSBitcoinKit/Network/Peer/PeerGroup.swift, HSBitcoinKit/HSBitcoinKit/Network/Peer/PeerManager.swift, HSBitcoinKit/HSBitcoinKitTests/Managers/FeeRateManagerTests.swift, HSBitcoinKit/HSBitcoinKitTests/Network/New Group/PeerGroupTests/IPeerGroupTests.swift, HSBitcoinKit/HSBitcoinKitTests/Network/New Group/PeerGroupTests/PeerDelegateTests.swift, HSBitcoinKit/HSBitcoinKitTests/Network/New Group/PeerManagerTests.swift
- PeerGroup#downloadBlockchain(peer:) doesn't trigger next iteration unless currentPeer is syncPeer
- PeerGroup#sendPendingTransactions() requires around half of peers to be connected and synced
closes #273
=> Fix potential bug that may cause PeerGroup sync loop (#273)

BitcoinCore/BitcoinCore/Managers/InitialSync/InsightApi.swift
to fix bug with empty addresses field 
closes #383
=> Make insightApi parameters in outputs optional

BitcoinCore/BitcoinCore/Blocks/BlockSyncer.swift, BitcoinCore/BitcoinCore/Core/BitcoinCoreBuilder.swift, BitcoinCore/BitcoinCoreTests/Blocks/BlockSyncerTests.swift
- If the last block in storage is older than the lastCheckpointBlock set to network, then it uses bip44CheckpointBlock
closes #389
=> Fix bug with updated checkpoint (#389)

BitcoinCore/BitcoinCore/Core/BitcoinCoreBuilder.swift, BitcoinCore/BitcoinCore/Managers/BloomFilterManager.swift, BitcoinCore/BitcoinCore/Transactions/TransactionCreator.swift, BitcoinCore/BitcoinCore/Transactions/TransactionProcessor.swift, BitcoinCore/BitcoinCoreTests/Managers/BloomFilterManagerTests.swift, BitcoinCore/BitcoinCoreTests/Transactions/TransactionCreatorTests.swift, BitcoinCore/BitcoinCoreTests/Transactions/TransactionProcessorTests.swift
- TransactionProcessor doesn't emit 'onUpdate' event to it's listener if transaction existed in DB with blockHash and it's coming from mempool
- TransactionProcessor trows exception in 'processCreated' if the transaction expires the bloom filter
- TransactionCreator regenerates bloomfilter if transaction processor throws BloomFilterExpired exception
- Remove bloomfilter.filter mutation check. It's useless, because filter is changed even if the elements are not changed
closes #395
=> Bugfixes (#395)

BitcoinCore/BitcoinCore/Blocks/InitialBlockDownload.swift, BitcoinCore/BitcoinCore/Core/KitStateProvider.swift, BitcoinCore/BitcoinCore/Core/Protocols.swift, BitcoinCore/BitcoinCore/Managers/SyncedReadyPeerManager.swift, BitcoinCore/BitcoinCore/Network/TransactionSender.swift
- Wrap peers dictionary in SyncedReadyPeersManager to dispatch queue
- 1 synced peer is enough for kit to be synced
closes #400 
closes #401
=> Bugfixes (#400, #401)

BitcoinCore/BitcoinCore/Blocks/InitialBlockDownload.swift
Some peers fail to send InventoryMessage within expected time and become 'synced' in InitialBlockDownload without sending all of their blocks. In such case, we shouldn't set 'synced' state to the kit
closes #426
=> Don't call ISyncStateListener#syncFinished if peer hasn't sent all of it's blocks

BitcoinCore/BitcoinCore/Transactions/Builder/TransactionBuilder.swift
=> Set 0xFFFFFFFE to nSequence to inputs to enable nLockTime and disable Replace-By-Fee

BitcoinCashKit.swift.podspec, BitcoinCore.swift.podspec, BitcoinKit.swift.podspec, DashKit.swift.podspec, Hodler.swift.podspec
To avoid conflict with podspecs dependencies versions.
=> Update versions to 0.13.1 for all kits. 

BitcoinCore/Classes/Transactions/TransactionConflictsResolver.swift
- TransactionConflictsResolver#transactionsConflicting shouldn't filter out transactions already having conflictingTxHash set. PendingTransactionsProcessor should know if any conflicting transactions exist.
=> Fix bug in TransactionConflictsResolver

BitcoinCashKit/Classes/Network/MainNet.swift, BitcoinCore/Classes/Core/BitcoinCoreBuilder.swift, BitcoinCore/Classes/Core/Protocols.swift, BitcoinCore/Classes/Helpers/UnspentOutputSelectorChain.swift, BitcoinCore/Classes/Managers/UnspentOutputSelector.swift, BitcoinCore/Classes/Managers/UnspentOutputSelectorSingleNoChange.swift, BitcoinCore/Classes/Models/Output.swift, BitcoinCore/Classes/Transactions/Builder/DustCalculator.swift, BitcoinCore/Classes/Transactions/Builder/InputSetter.swift, BitcoinKit/Classes/Network/MainNet.swift, DashKit/Classes/Core/DashKit.swift, DashKit/Classes/Network/MainNet.swift, Example/Tests/BitcoinCore/Managers/UnspentOutputSelectorOldTests.swift, Example/Tests/BitcoinCore/Managers/UnspentOutputSelectorSingleNoChangeTests.swift, Example/Tests/BitcoinCore/Managers/UnspentOutputSelectorTests.swift, LitecoinKit/Classes/Network/MainNet.swift
- UnspentOutputSelector and UnspentOutputSelectorSingleNoChange must calculate dust for "recipient" and "change" outputs separately
- DustCalculator must calculate dust for .p2wpkhSh as for nonSegwit transaction
=> Fix bug with dust validation

BitcoinCore/Classes/Network/Peer/PeerAddressManager.swift, BitcoinCore/Classes/Network/Peer/PeerAddressManagerState.swift, BitcoinCore/Classes/Network/Peer/PeerConnection.swift
- Wrap all PeerAddressManager calls to storage and state in a serial queue
=> Unwrap optional baseAddress of a unsafe bytes object in PeerConnection

BitcoinCore/Classes/Managers/UnspentOutputSelector.swift, BitcoinCore/Classes/Managers/UnspentOutputSelectorSingleNoChange.swift, BitcoinCore/Classes/Models/Output.swift, BitcoinCore/Classes/Network/TransactionSender.swift, BitcoinCore/Classes/Storage/GrdbStorage.swift, Example/Tests/BitcoinCore/Managers/UnspentOutputSelectorSingleNoChangeTests.swift, Example/Tests/BitcoinCore/Managers/UnspentOutputSelectorTests.swift
- Firstly, select outputs formerly failed to spend. This is to avoid a following case:
1. A transaction TX1 is failed to be spent. (We fail to get confirmation that it's in mempool)
2. It's actually added to mempool.
3. A user tries to send the same amount for the second time (TX2). If TX2 doesn't use outputs spent by TX1, it may be successfully sent, thus, having both TX1 and TX2 being sent.
- Invalidate transaction if cannot be broadcasted for 3 times
=> Improve unspent output selection logic
